### ISSUE TITLE
Allow wildcard node-label / relationship-type configuration

### ISSUE THREAD

**Issue by fskpf** [yWorks/yfiles-jupyter-graphs-for-neo4j#10]
Similar to how graphdatascience algorithms filter for nodeLabels / relationshipTypes (e.g. [here](https://neo4j.com/docs/graph-data-science/current/algorithms/louvain/)), we should also allow a special wildcard type that just matches all types.

Something like this
```
add_node_configuration("*", config)
add_relationship_configuration("*", config)
```

Maybe we should then go the full step and directly add support for type arrays:
```
add_node_configuration(["*"], config)
add_relationship_configuration(["*"], config)
```

**Comment by yGuy** [comment]
I like the idea. Ideally, this would work a bit like in CSS so that later, more specific matching declarations overwrite those in the "base" declaration.
